const noticias = [
    {
        id: 1,
        imagen: "https://media.urgente24.com/p/47e80a2a22bf3a7e1f23e257fa4a4e85/adjuntos/319/imagenes/002/979/0002979734/lbz7jgaj5ncsrh7yunzy2af2qujpg.jpg",
        minititulo: "Descenso al rojo vivo",
        titulo: "Expulsión de Ascacíbar complica a Estudiantes ante Unión en una final anticipada",
        miniinfo: "El mediocampista del Pincha vio la roja en un partido caliente por la permanencia. El duelo está 1-1 y arde Santa Fe.",
        info: "Estudiantes de La Plata sufre un duro golpe en su visita a Santa Fe: Santiago Ascacíbar fue expulsado a los 67 minutos y deja a su equipo con 10 jugadores en un momento clave del partido ante Unión. Ambos equipos llegan al duelo ocupando los últimos puestos de la tabla —Estudiantes en el 22.º lugar y Unión en el 23.º— y se juegan la permanencia en esta fecha crucial. El partido comenzó con ventaja para el Pincha gracias al gol de Mauro Boselli a los 16', pero el local reaccionó antes del descanso con el empate de Jerónimo Domina a los 43’. El partido, muy disputado y friccionado, ha acumulado varias amonestaciones, y la expulsión de Ascacíbar puede inclinar la balanza en favor del Tatengue. Restan 20 minutos decisivos en una verdadera final por evitar el descenso.",
        autor: "Juan Pérez",
        fecha: "Hace 5 minutos",
        likes: 0
    },

    {
        id: 2,
        imagen: "https://a2.espncdn.com/combiner/i?img=%2Fphoto%2F2024%2F1209%2Fr1425933_1296x729_16%2D9.jpg",
        minititulo: "primera",
        titulo: "La liga argentina tendrá 22 equipos en la próxima temporada",
        miniinfo: "Cada vez más cerca el regreso a una liga de 20 equipos como en los viejos tiempos.",
        info: "La AFA confirmó que la próxima temporada de la Liga Profesional se jugará con 22 equipos, recortando de a poco la cantidad de participantes. Esta medida sigue el plan de reducción progresiva, con el objetivo de volver a un torneo de 20 clubes como era habitual en décadas pasadas. La decisión generó opiniones divididas, pero ya se habla de que en dos años podría completarse el formato tradicional.",
        autor: "Redacción FPT",
        fecha: "Hace 1 dia",
        likes: 0
    },
    {
        id: 3,
        imagen: "https://media.tycsports.com/files/2024/09/23/769284/israel-damonte-previa-_862x485.webp?v=1",
        minititulo: "Crisis en Junín",
        titulo: "Sarmiento despide a su DT tras una racha desastrosa y se hunde en la tabla",
        miniinfo: "El Verde de Junín decidió cortar por lo sano tras una campaña alarmante: solo 4 triunfos en 28 fechas.",
        info: "Sarmiento de Junín atraviesa uno de los momentos más delicados de su historia reciente. La dirigencia tomó la decisión de despedir al entrenador luego de caer al último puesto del campeonato, con un balance preocupante: apenas 4 partidos ganados, 5 empatados y 19 derrotas en 28 fechas disputadas. El equipo tiene la peor defensa del torneo con 59 goles en contra y apenas ha convertido 26. La crisis deportiva se refleja también en lo anímico, y en las últimas horas se filtraron tensiones en el vestuario. Ahora, la institución busca un reemplazo urgente para encarar las últimas seis fechas y evitar un descenso que parece inminente.",
        autor: "Juan Pérez",
        fecha: "Hace 1 dia",
        categoria: "Fútbol Argentino",
        likes: 0
    },
    {
        id: 4,
        imagen: "https://www.infobae.com/resizer/v2/3GKINY6VHNHSXOCBHV2VCW4Z5Q?auth=fefde4c7b3f36bc0850a278a3adb721cb7c7b7b22bb784c272cd1db040cb3fb0&smart=true&width=992&height=558&quality=85",
        minititulo: "hola",
        titulo: "dadwdwa",
        miniinfo: "En un hallazgo sin precedentes, investigadores encontraron evidencia de una nueva especie de unicornio...",
        info: "fwafwa",
        autor: "Juan Pérez",
        fecha: "2025-01-07",
        likes: 0,
    },
    {
        id: 5,
        imagen: "https://www.infobae.com/resizer/v2/3GKINY6VHNHSXOCBHV2VCW4Z5Q?auth=fefde4c7b3f36bc0850a278a3adb721cb7c7b7b22bb784c272cd1db040cb3fb0&smart=true&width=992&height=558&quality=85",
        minititulo: "hola",
        titulo: "dadwdwa",
        miniinfo: "En un hallazgo sin precedentes, investigadores encontraron evidencia de una nueva especie de unicornio...",
        info: "fwafaw",
        autor: "Juan Pérez",
        fecha: "2025-01-07",
        likes: 0,
    },
    {
        id: 6,
        imagen: "https://www.infobae.com/resizer/v2/3GKINY6VHNHSXOCBHV2VCW4Z5Q?auth=fefde4c7b3f36bc0850a278a3adb721cb7c7b7b22bb784c272cd1db040cb3fb0&smart=true&width=992&height=558&quality=85",
        minititulo: "hola",
        titulo: "dadwdwa",
        miniinfo: "En un hallazgo sin precedentes, investigadores encontraron evidencia de una nueva especie de unicornio...",
        info: "wfafa",
        autor: "Juan Pérez",
        fecha: "2025-01-07",
        likes: 0,
    },
    {
        id: 7,
        imagen: "https://www.infobae.com/resizer/v2/3GKINY6VHNHSXOCBHV2VCW4Z5Q?auth=fefde4c7b3f36bc0850a278a3adb721cb7c7b7b22bb784c272cd1db040cb3fb0&smart=true&width=992&height=558&quality=85",
        minititulo: "hola",
        titulo: "dadwdwa",
        miniinfo: "En un hallazgo sin precedentes, investigadores encontraron evidencia de una nueva especie de unicornio...",
        info: "afwfwaf",
        autor: "Juan Pérez",
        fecha: "2025-01-07",
        likes: 0,
    },
    {
        id: 8,
        imagen: "https://www.infobae.com/resizer/v2/3GKINY6VHNHSXOCBHV2VCW4Z5Q?auth=fefde4c7b3f36bc0850a278a3adb721cb7c7b7b22bb784c272cd1db040cb3fb0&smart=true&width=992&height=558&quality=85",
        minititulo: "hola",
        titulo: "dadwdwa",
        miniinfo: "En un hallazgo sin precedentes, investigadores encontraron evidencia de una nueva especie de unicornio...",
        info: "faefeaf",
        autor: "Juan Pérez",
        fecha: "2025-01-07",
        likes: 0,
    },
];

export default noticias;


/*{
        id: 1,
        imagen: "",
        minititulo: "Descubren una nueva especie de unicornio en Argentina",
        titulo: "",
        resumen: "Científicos aseguran que el hallazgo podría cambiar la historia.",
        contenido: "En un hallazgo sin precedentes, investigadores encontraron evidencia de una nueva especie de unicornio...",
        autor: "Juan Pérez",
        fecha: "2025-01-07",
        categoria: "Ciencia",
        imagenUrl: "https://via.placeholder.com/150",
        likes: 0,
        comentarios: [],
        destacado: false,
    },*/
